### ISSUE TITLE
Underline style links

### ISSUE THREAD

**Issue by sindresorhus** [johnotander/pixyll#171]
I really like how the medium.com links look:

<img width="701" alt="screen shot 2015-07-11 at 00 34 51" src="https://cloud.githubusercontent.com/assets/170270/8630345/aae0f37c-2764-11e5-90f7-9fd3a7616dd6.png">

https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841

They're underlined by default.

Would you be open to switching to that style? No worries if not, then I'll just do it in my fork.

When reading I get easily distracted by the current blue color.

**Comment by johnotander** [comment]
I'd definitely like to switch to that style, I agree that it's less distracting for long form content. They won't be able to look as [pretty as Medium's](https://medium.com/designing-medium/crafting-link-underlines-on-medium-7c03a9274f9), but `text-decoration: underline` with the body text color should be pretty close.

Also, I'll break out the link configuration (decoration/color/etc) to variables so they can be tweaked really easily, too.

**Comment by sindresorhus** [comment]
> I'd definitely like to switch to that style, I agree that it's less distracting for long form content.

Awesome! :)

> They won't be able to look as pretty as Medium's,

I think you can. Looks like they're using a simpler solution now. At least in Chrome:

```css
body.is-withMagicUnderlines .markup--anchor {
    text-decoration: none;
    background-image: linear-gradient(to bottom, rgba(0,0,0,0) 50%, rgba(0,0,0,0.6) 50%);
    background-repeat: repeat-x;
    background-size: 2px 2px;
    background-position: 0 23px
}
```
