### ISSUE TITLE
Link underline disappears on medium view

### ISSUE THREAD

**Issue by alxmjo** [johnotander/pixyll#233]
When the window is resized to a medium-sized view (based on the viewport setting) the link underlines disappear (at least for me on Chrome and Safari). 

Changing the a rule in _links.scss from:

```css
a {
  color: $link-color;
  background-image: linear-gradient(to top,
    rgba(0,0,0,0) 13%,
    rgba($link-color,.8) 13%,
    rgba($link-color,.8) 17%,
    rgba(0,0,0,0) 17%
}
```

to

```css
a {
  color: $link-color;
  background-image: linear-gradient(to top,
    rgba(0,0,0,0) 13%,
    rgba($link-color,.8) 13%,
    rgba($link-color,.8) 18%, // This is the only line that's different
    rgba(0,0,0,0) 17%
}
```

fixes the problem for me.
